FIX(APP-29) Set up the Icon Layer in the app

diff --git a/.github/workflows/cherry-pick_pr.yml b/.github/workflows/cherry-pick_pr.yml
--- a/.github/workflows/cherry-pick_pr.yml
+++ b/.github/workflows/cherry-pick_pr.yml
@@ -37,47 +37,48 @@ jobs:
         id: regex-match
         with:
           text: ${{ github.event.commits[0].message }}
-          regex: '^/FIX+\([A-Z]+\-[0-9]+\)+\:/'
+          regex: '/^FIX+\([A-Z]+\-[0-9]+\)+\:/'
 
-      # - if: ${{ !success() }}
-      #   run: |
-      #     echo ${{steps.regex-match.outputs.match}}
+      - if: ${{ !success() }}
+        run: |
+          echo ${{steps.regex-match.outputs.match}}
       
-      - name: "Checking commit-message format..."
-        if: ${{ !success() && !startsWith(github.event.commits[0].message, 'FIX(') }};then
-            echo -e "Your commit-message format is not valid:\n$github.event.commits[0].message\n"
-            echo "Valid format examples:"
-            echo "[PSBO-123] My commit message"
-            echo "[hotfix] My commit message"
-            exit 1
-          else
-            echo "Well done! Your commit-message is valid."
-            exit 0
-          fi
-        uses: neonidian/teams-notify-build-status@v3
-        with:
-          webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
-          message: >-
-            Hi ${{github.actor}},
+      # - if: ${{ !success() && !startsWith(github.event.commits[0].message, 'FIX(') }};then
+      #       echo -e "Your commit-message format is not valid:\n$github.event.commits[0].message\n"
+      #       echo "Valid format examples:"
+      #       echo "[PSBO-123] My commit message"
+      #       echo "[hotfix] My commit message"
+      #       exit 1
+      #     else
+      #       echo "Well done! Your commit-message is valid."
+      #       exit 0
+      #     fi
+      #   # uses: neonidian/teams-notify-build-status@v3
+      #   # with:
+      #   #   webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
+      #   #   message: >-
+      #   #     Hi ${{github.actor}},
             
-            We require pull request titles to follow the PR Title Conventions and it looks like your proposed title needs to be adjusted.
-          status: Failure
+      #   #     We require pull request titles to follow the PR Title Conventions and it looks like your proposed title needs to be adjusted.
+      #   #   status: Failure
 
 
-        # if: ${{ !success() && !startsWith('FIX',github.event.commits[0].message) && !contains(fromJson('["-",":"]'), github.event.commits[0].message)}} 
-        # run: |
-        #   echo "Test Pass with valid PR"
-        #   echo  ${{startsWith('FIX',github.event.commits[0].message)}}
-        #   echo  ${{contains('FIX', github.event.commits[0].message)}}
-        #   echo  ${{github.event.commits[0].message}}
-        # uses: neonidian/teams-notify-build-status@v3
-        # with:
-        #   webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
-        #   message: >-
-        #     Hi ${{github.actor}},
+      #   # if: ${{ !success() && !startsWith('FIX',github.event.commits[0].message) && !contains(fromJson('["-",":"]'), github.event.commits[0].message)}} 
+      #   # run: |
+      #   #   echo "Test Pass with valid PR"
+      #   #   echo  ${{startsWith('FIX',github.event.commits[0].message)}}
+      #   #   echo  ${{contains('FIX', github.event.commits[0].message)}}
+      #   #   echo  ${{github.event.commits[0].message}}
+      #   # uses: neonidian/teams-notify-build-status@v3
+      #   # with:
+      #   #   webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
+      #   #   message: >-
+      #   #     Hi ${{github.actor}},
             
-        #     We require pull request titles to follow the PR Title Conventions and it looks like your proposed title needs to be adjusted.
-        #   status: Failure
+      #   #     We require pull request titles to follow the PR Title Conventions and it looks like your proposed title needs to be adjusted.
+      #   #   status: Failure
+
+
       - name: Create Cherry-pick PR
         if: ${{ startsWith(github.ref, 'refs/heads/release') && success() }}
         uses: devops-infra/action-pull-request@v0.5.5
