Feat/app-32 yml file changed

diff --git a/.github/workflows/cherry-pick_pr.yml b/.github/workflows/cherry-pick_pr.yml
--- a/.github/workflows/cherry-pick_pr.yml
+++ b/.github/workflows/cherry-pick_pr.yml
@@ -23,3 +23,11 @@ jobs:
           get_diff: true
           target_branch : 'main'
           source_branch : ${{ github.head_ref || github.ref_name }} 
+     
+      - uses: actions/checkout@v3
+      - name: List files with merge conflict markers
+        run: git --no-pager grep "<<<<<<<" ":(exclude).github/" || true
+      - name: Fail or succeed job if any files with merge conflict markers have been checked in
+        # Find lines containing "<<<<<<<", then count the number of lines.
+        # 0 matching lines results in exit code 0, i.e. success.
+        run: exit $(git grep "<<<<<<<" ":(exclude).github/" | wc --lines)
