Tag WIP

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,8 +15,12 @@ jobs:
     steps:
       - name: Verify release branch not exists
         run: |
-          if git ls-remote --heads git@github.com:user/repo.git refs/heads/[inputs.release_version] | wc -l; then exit 1; else exit 0; fi
-
+          git ls-remote --heads git@github.com:user/repo.git refs/heads/[inputs.release_version]
+           PARAMS=${git ls-remote --heads git@github.com:user/repo.git refs/heads/[inputs.release_version] }
+          if [[ ! "$PARAMS" =~ 1 ]]; then
+            echo "Invalid /changelog-entry command"
+            exit 1
+          fi
       # - name: Checkout Code
       #   uses: actions/checkout@v3
       
